### ISSUE TITLE
Support the OTel Meter namespace

### ISSUE THREAD

**Issue by jmacd** [marwan-at-work/otel-exporter-datadog#2]
There is a new "Namespace" field in the exported metric record. See https://github.com/open-telemetry/opentelemetry-specification/pull/408

**Comment by marwan-at-work** [comment]
This is done here https://github.com/marwan-at-work/otel-exporter-datadog/commit/7691e46da68fa93ea8b7708a4c60d9fc2da88466

We are now using `record.Descriptor().LibraryName()` -- definitely let me know if that's what you had in mind. Thank you!

**Comment by jmacd** [comment]
https://github.com/marwan-at-work/otel-exporter-datadog/commit/7691e46da68fa93ea8b7708a4c60d9fc2da88466#r38377881

**Comment by jmacd** [comment]
In the comment, I suggested using a tag name for the library, not prepending it as a namespace. I believe OTel has a standard convention for the tag name, but I'm don't recall it immediately.

**Comment by marwan-at-work** [comment]
@jmacd I see. It's also worth noting that they can also add it through here https://github.com/marwan-at-work/otel-exporter-datadog/blob/master/datadog.go#L44 

For now I can remove the namespace-metricname-prepending, (or maybe make it optional/customizable similar to SpanNameFormatter in othttp) 

And lastly, yes I'd love to know the name of the tag, for now I'll just call it `namespace` -- but I'm skeptical of what happens if a user wants to override this tag name, which is why I think they should just use the `Tags` option I linked to above.

**Comment by marwan-at-work** [comment]
For reference: https://github.com/marwan-at-work/otel-exporter-datadog/pull/4
